version: '3.8'

services:
  zipper-bot:
    build: .
    restart: always
    container_name: fast_zipper
    env_file:
      - .env
    volumes:
      - ./zipper_state.db:/app/zipper_state.db
      - ./downloads:/app/downloads
      # THIS LINE FIXES THE "NOT ADMIN" / RE-LOGIN ISSUE
      - ./sessions:/app/sessions
